### ISSUE TITLE
1. qualify_search Error 2. Need a function to retrieve courses_info with a list of course.number

### ISSUE THREAD

**Issue by ChenhaoWang1999** [SelendisErised/Columbia-Course-Recommendation-System#2]
Branch: Login-FrontENd
1. There's a SQL error with search_engine.qualify_search(wish_list, search_key)
 The calling of this function is at the line 200 server.py (you can uncomment this and comment line 201 to test it)
![image](https://user-images.githubusercontent.com/76039657/202605845-cb452ee1-cc67-4ff4-b91e-2cdedd3e84c5.png)

2. wish_list is a list of course numbers stored in our server.py (e.x. ['COMS6998E002', 'COMS6156E001', 'COMS4111W003']). A function to retrieve all information (return object type is the same as the return of search_engine.ambiguous_search(search_key) ) of the courses in this wish_list is needed for frontend displaying.
![image](https://user-images.githubusercontent.com/76039657/202607794-54817828-6539-4206-b5ae-a90639e4da81.png)

**Comment by xinhuang09** [comment]
Issues solved, lastest pushed to main.
